# data
reshape_size: 16
scale_factor: 2
data_path: example8/

# model 
channels_init: 16
final_out_channels: 20
model_name: recon_small_pde_large

# hyper parameters
num_epochs: 1000
batch_size: 8
learning_rate: 0.001

# loss functions
beta: 0.5
alpha: 0.25
scheduler_gamma: 0.99





