# data
nvox: 64
nsamples: 500
data_path: example8/

# model 
channels_init: 16
model_name: recon_small_pde_large

# hyper parameters
num_epochs: 1000
batch_size: 8
learning_rate: 0.001

# loss functions
boundary_recon: 0.85
flow_pde: 0.95
background_recon: 1.0

# optimizer
scheduler_gamma: 0.99

# navier-stokes parameters
rho: 1
mu: 1
gx: 0
gy: 0
gz: 0





