# data
reshape_size: 16
data_path: example8/

# model 
channels_init: 16
model_name: standardized_test

# hyper parameters
num_epochs: 1000
batch_size: 8
learning_rate: 0.001

# loss functions
beta: 0.5
alpha: 0.25
scheduler_gamma: 0.99





